#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Theme Settings
PRIMARY_FG=white

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export EDITOR=vim

# zsh customs
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.zsh_history

# allow auto completition
fpath=(/usr/local/share/zsh-completions $fpath)

# force UTF-8
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Add User Info for Ansible Deploys
export MS_USER=Rob
export DEFAULT_USER="$USER"

# add ellipsis to paths
export PATH=~/.ellipsis/bin:$PATH

# add default key behaviour
bindkey -e

# enable powerline
powerline-daemon -q

# uncomment this line to enable full support of powerline
#. /usr/local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh

# Python
export PATH="/usr/local/opt/python/libexec/bin:$PATH"

# Go Development
if [ -d "$HOME/GolangProjects" ]
then

    export GOPATH=$HOME/GolangProjects
    export GOROOT=/usr/local/opt/go/libexec
    export PATH=$PATH:$GOPATH/bin
    export PATH=$PATH:$GOROOT/bin
fi
