#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# add default key behaviour
bindkey -e

# Theme Settings
PRIMARY_FG=white

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export EDITOR=vim

# zsh customs
HISTFILE=~/.zsh_history
SAVEHIST=1000
fpath=(/usr/local/share/zsh-completions $fpath)

# force UTF-8
export LC_ALL=en_US.UTF-8 
export LANG=en_US.UTF-8

# Add User Info for Ansible Deploys
export MS_USER=Rob

# add ellipsis to paths
export PATH=~/.ellipsis/bin:$PATH
